# Generated by Django 4.1.5 on 2023-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
